export const distensionInfo = [
  {
    country: "USA",
    flag: "/flag/usa.png",
    id: 1,
    subTitle:
      "We strive to build a global community where quality higher education empowers curious learners and encourages them to transform their  lives. We deploy cutting-edge technologies on the Northway platform  to simplify students international education journeys. We blend  technology and innovation to transform the higher education  landscape with institutions, partners, and industry stakeholders.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co.com/m5cGsws/columbia.webp",
    title4: "Columbia University",
    img5: "https://i.ibb.co.com/m0qN4c0/priceton.webp",
    title5: "Princeton University",
    img6: "https://i.ibb.co.com/gdjk67K/harvard.webp",
    title6: "Harvard University",
    img7: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title7: "Yale University",
    img8: "https://i.ibb.co.com/5YwWNfz/yale.webp",
    title8: "Stanford University",
    img9: "../../public/CountryLogo/nyu.jpg",
    title9: "Nyc University",
  },
  {
    country: "Ireland",
    flag: "/flag/ireland.png",
    id: 2,
    subTitle:
      "Ireland is home to some of the world’s leading universities and research institutions. Irish degrees are internationally respected and provide excellent opportunities for career advancement, both in Europe and globally.",
    img1: "/CountryLogo/Athlone Institute Of Technology.jpg",

    title1: "Athlone Institute Of Technology",
    img2: "/CountryLogo/Dundalk Institute of Technology.jpg",
    title2: "Dundalk Institute of Technology",
    img3: "/CountryLogo/Munster Technological University.jpg",
    title3: "Munster Technological University",
    img4: "/CountryLogo/National University of Ireland.jpg",
    title4: "National University of Ireland",
    img5: "/CountryLogo/Trinity College Dublin.jpg",
    title5: "Trinity College Dublin",
    img6: "/CountryLogo/Waterford Institute Of Technology.jpg",
    title6: "Waterford Institute Of Technology",
    img7: "/CountryLogo/University College Dublin.jpg",
    title7: "University College Dublin.jpg",
    img8: "/CountryLogo/University of Galway.jpg",
    title8: "University of Galway",
    img9: "/CountryLogo/South East Technological University.jpg",
    title9: "South East Technological University",
  },
  {
    country: "Europe",
    flag: "/flag/europe.png",
    id: 3,
    subTitle:
      "Europe is home to some of the world’s most prestigious universities. Institutions like Oxford, Cambridge, Sorbonne, and ETH Zurich offer education at the highest standards, and degrees from these universities are highly regarded worldwide.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "Canada",
    flag: "/flag/canada.png",
    id: 4,
    subTitle:
      "Canada is one of the most popular destinations for international students, known for its high-quality education, cultural diversity, and student-friendly environment. Whether you're seeking an undergraduate degree, graduate studies, or vocational training, studying in Canada offers a path to academic success and global opportunities.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "Australia",
    flag: "/flag/australia.png",
    id: 5,
    subTitle:
      "Australia is home to several universities that rank among the best in the world. Institutions like the University of Melbourne, Australian National University, and the University of Sydney offer a wide range of courses and research opportunities that meet international standards.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "Austria",
    flag: "/flag/Austria.png",
    id: 6,
    subTitle:
      "Austria boasts several world-renowned universities, such as the University of Vienna, Graz University of Technology, and Vienna University of Technology. These institutions offer a wide range of programs in various fields, including arts, sciences, engineering, and social sciences.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "Germany",
    flag: "flag/Germany.png",
    id: 7,
    subTitle:
      "Germany is known for its world-class universities and academic excellence. With a strong focus on research and development, German institutions consistently rank among the best globally, offering a wide range of programs across various fields.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "Japan",
    flag: "/flag/Japan.png",
    id: 8,
    subTitle:
      "Japan is home to several top-ranking universities that offer a wide range of programs in English, particularly in fields such as engineering, science, technology, and business. Institutions like the University of Tokyo, Kyoto University, and Osaka University are recognized globally for their academic excellence.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "China",
    flag: "/flag/China.png",
    id: 9,
    subTitle:
      "China is rapidly emerging as a leading destination for international students, offering a unique blend of ancient culture and modern innovation. With a robust education system and numerous opportunities for personal and professional growth, studying in China is an enriching experience.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
  {
    country: "South Korea",
    flag: "/flag/South_Korea.png",
    id: 10,
    subTitle:
      "South Korea is home to several top-ranking universities, such as Seoul National University, KAIST, and POSTECH. These institutions offer a wide range of programs in various fields, particularly in technology, engineering, and business",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",

    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title4: "Arizona State University, Phoenix, Arizona",
    img5: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title5: "University of Connecticut, Connecticut (Public Ivy)",
    img6: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title6: "University of California, Riverside, California",
    img7: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title7: "University of Connecticut, Connecticut (Public Ivy)",
    img8: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title8: "Stanford University",
    img9: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title9: "Stanford University",
  },
];
