export const distensionInfo = [
  {
    country: "USA",
    flag: "/flag/usa.png",
    id: 1,
    subTitle:
      "We strive to build a global community where quality higher education empowers curious learners and encourages them to transform their  lives. We deploy cutting-edge technologies on the Northway platform  to simplify students international education journeys. We blend  technology and innovation to transform the higher education  landscape with institutions, partners, and industry stakeholders.",
    img1: "https://i.ibb.co/d23LGHN/uni1-66db36043eb12.webp",
    title1: "University of Connecticut, Connecticut (Public Ivy)",
    img2: "https://i.ibb.co/r0F2P81/uni2-66db364355225.webp",
    title2: "Arizona State University, Phoenix, Arizona",
    img3: "https://i.ibb.co/9GZGLMx/uni3-66db368f59e38.webp",
    title3: "University of California, Riverside, California",
    img4: "https://i.ibb.co.com/m5cGsws/columbia.webp",
    title4: "Columbia University",
    img5: "https://i.ibb.co.com/m0qN4c0/priceton.webp",
    title5: "Princeton University",
    img6: "https://i.ibb.co.com/gdjk67K/harvard.webp",
    title6: "Harvard University",
    img7: "https://i.ibb.co.com/G2Kpn2T/stanford.webp",
    title7: "Yale University",
    img8: "https://i.ibb.co.com/5YwWNfz/yale.webp",
    title8: "Stanford University",
    img9: "/CountryLogo/nyu.jpg",
    title9: "Nyc University",
  },
  {
    country: "Ireland",
    flag: "/flag/ireland.png",
    id: 2,
    subTitle:
      "Ireland is home to some of the world’s leading universities and research institutions. Irish degrees are internationally respected and provide excellent opportunities for career advancement, both in Europe and globally.",
    img1: "/CountryLogo/Athlone Institute Of Technology.jpg",

    title1: "Athlone Institute Of Technology",
    img2: "/CountryLogo/Dundalk Institute of Technology.jpg",
    title2: "Dundalk Institute of Technology",
    img3: "/CountryLogo/Munster Technological University.jpg",
    title3: "Munster Technological University",
    img4: "/CountryLogo/National University of Ireland.jpg",
    title4: "National University of Ireland",
    img5: "/CountryLogo/Trinity College Dublin.jpg",
    title5: "Trinity College Dublin",
    img6: "/CountryLogo/Waterford Institute Of Technology.jpg",
    title6: "Waterford Institute Of Technology",
    img7: "/CountryLogo/University College Dublin.jpg",
    title7: "University College Dublin.jpg",
    img8: "/CountryLogo/University of Galway.jpg",
    title8: "University of Galway",
    img9: "/CountryLogo/South East Technological University.jpg",
    title9: "South East Technological University",
  },
  {
    country: "Europe",
    flag: "/flag/europe.png",
    id: 3,
    subTitle:
      "Europe is home to some of the world’s most prestigious universities. Institutions like Oxford, Cambridge, Sorbonne, and ETH Zurich offer education at the highest standards, and degrees from these universities are highly regarded worldwide.",
    img1: "../../public/CountryLogo/Europe/ETH Zurich.jpg",

    title1: "ETH Zurich",
    img2: "../../public/CountryLogo/Europe/Imperial College London.jpg",
    title2: "Imperial College London",
    img3: "../../public/CountryLogo/Europe/London School of Economics and Political Science.jpg",
    title3: "London School of Economics and Political Science",
    img4: "../../public/CountryLogo/Europe/University of Amsterdam.jpg",
    title4: "University of Amsterdam",
    img5: "../../public/CountryLogo/Europe/University of Bristol.jpg",
    title5: "University of Bristol",
    img6: "../../public/CountryLogo/Europe/University of Cambridge.jpg",
    title6: "University of Cambridge",
    img7: "../../public/CountryLogo/Europe/University of Copenhagen.jpg",
    title7: "University of Copenhagen",
    img8: "../../public/CountryLogo/Europe/University of Edinburgh.jpg",
    title8: "University of Edinburgh",
    img9: "../../public/CountryLogo/Europe/University of Oxford.jpg",
    title9: "University of Oxford",
  },
  {
    country: "Canada",
    flag: "/flag/canada.png",
    id: 4,
    subTitle:
      "Canada is one of the most popular destinations for international students, known for its high-quality education, cultural diversity, and student-friendly environment. Whether you're seeking an undergraduate degree, graduate studies, or vocational training, studying in Canada offers a path to academic success and global opportunities.",
    img1: "/CountryLogo/Canada/Concordia University.jpg",

    title1: "Concordia University",
    img2: "/CountryLogo/Canada/McGill University.jpg",
    title2: "McGill University",
    img3: "/CountryLogo/Canada/Queen's University.jpg",
    title3: "Queen's University",
    img4: "/CountryLogo/Canada/University of Alberta.jpg",
    title4: "University of Alberta",
    img5: "/CountryLogo/Canada/University of British Columbia.jpg",
    title5: "University of British Columbia",
    img6: "/CountryLogo/Canada/University of Montreal.jpg",
    title6: "University of Montreal",
    img7: "/CountryLogo/Canada/University of Toronto.jpg",
    title7: "University of Toronto",
    img8: "/CountryLogo/Canada/University of Waterloo.jpg",
    title8: "University of Waterloo",
    img9: "/CountryLogo/Canada/York University.jpg",
    title9: "York University",
  },
  {
    country: "Australia",
    flag: "/flag/australia.png",
    id: 5,
    subTitle:
      "Australia is home to several universities that rank among the best in the world. Institutions like the University of Melbourne, Australian National University, and the University of Sydney offer a wide range of courses and research opportunities that meet international standards.",
    img1: "/CountryLogo/University of Melbourne.jpg",
    title1: "Melbourne University",
    img2: "/CountryLogo/University of Adelaide.jpg",
    title2: "Adelaide University",
    img3: "/CountryLogo/University of Newcastle.jpg",
    title3: "University of Newcastle",
    img4: "/CountryLogo/University of Sydney.jpg",
    title4: "University of Sydney",
    img5: "/CountryLogo/University of Technology Sydney.jpg",
    title5: "University of Technology Sydney",
    img6: "/CountryLogo/Victoria University.jpg",
    title6: "Victoria University",
    img7: "/CountryLogo/Royal Melbourne Institute of Technology.jpg",
    title7: "Royal Melbourne Institute of Technology",
    img8: "/CountryLogo/Deakin University.jpg",
    title8: "Deakin University",
    img9: "/CountryLogo/Monash University.jpg",
    title9: "Monash University",
  },
  {
    country: "Austria",
    flag: "/flag/Austria.png",
    id: 6,
    subTitle:
      "Austria boasts several world-renowned universities, such as the University of Vienna, Graz University of Technology, and Vienna University of Technology. These institutions offer a wide range of programs in various fields, including arts, sciences, engineering, and social sciences.",
    img1: "/CountryLogo/Austria/FH Joanneum.jpg",

    title1: "FH Joanneum",
    img2: "/CountryLogo/Austria/Johannes Kepler University.jpg",
    title2: "Johannes Kepler University",
    img3: "/CountryLogo/Austria/Medical University of Vienna.jpg",
    title3: "Medical University of Vienna",
    img4: "/CountryLogo/Austria/Paracelsus Medical University.jpg",
    title4: "Paracelsus Medical University",
    img5: "/CountryLogo/Austria/University of Graz.jpg",
    title5: "University of Graz",
    img6: "/CountryLogo/Austria/University of Innsbruck.jpg",
    title6: "University of Innsbruck",
    img7: "/CountryLogo/Austria/University of Leoben.jpg",
    title7: "University of Leoben",
    img8: "/CountryLogo/Austria/University of Salzburg.jpg",
    title8: "University of Salzburg",
    img9: "/CountryLogo/Austria/University of Vienna.jpg",
    title9: "University of Vienna",
  },
  {
    country: "Germany",
    flag: "flag/Germany.png",
    id: 7,
    subTitle:
      "Germany is known for its world-class universities and academic excellence. With a strong focus on research and development, German institutions consistently rank among the best globally, offering a wide range of programs across various fields.",
    img1: "/CountryLogo/Germany/Free University of Berlin.jpg",

    title1: "Free University of Berlin",
    img2: "/CountryLogo/Germany/Heidelberg University.jpg",
    title2: "Heidelberg University",
    img3: "/CountryLogo/Germany/Humboldt University of Berlin.jpg",
    title3: "Humboldt University of Berlin",
    img4: "/CountryLogo/Germany/Technical University of Munich.jpg",
    title4: "Technical University of Munich",
    img5: "/CountryLogo/Germany/Technical UniversityofBerlin.jpg",
    title5: "Technical UniversityofBerlin",
    img6: "/CountryLogo/Germany/University of Bonn.jpg",
    title6: "University of Bonn",
    img7: "/CountryLogo/Germany/University of Freiburg.jpg",
    title7: "University of Freiburg",
    img8: "/CountryLogo/Germany/University of Hamburg.jpg",
    title8: "University of Hamburg",
    img9: "/CountryLogo/Germany/University of Mannheim.jpg",
    title9: "University of Mannheim",
  },
  {
    country: "Japan",
    flag: "/flag/Japan.png",
    id: 8,
    subTitle:
      "Japan is home to several top-ranking universities that offer a wide range of programs in English, particularly in fields such as engineering, science, technology, and business. Institutions like the University of Tokyo, Kyoto University, and Osaka University are recognized globally for their academic excellence.",
    img1: "/CountryLogo/Japan/Chiba University.jpg",
    title1: "Chiba University",
    img2: "/CountryLogo/Japan/Hiroshima University.jpg",
    title2: "Hiroshima University",
    img3: "/CountryLogo/Japan/Kyoto University.jpg",
    title3: "Kyoto University",
    img4: "/CountryLogo/Japan/Kyushu University.jpg",
    title4: "Kyushu University",
    img5: "/CountryLogo/Japan/Osaka University.jpg",
    title5: "Osaka University",
    img6: "/CountryLogo/Japan/Tohoku University.jpg",
    title6: "Tohoku University",
    img7: "/CountryLogo/Japan/Tokyo Institute of Technology.jpg",
    title7: "Tokyo Institute of Technology",
    img8: "/CountryLogo/Japan/University of Tokyo.jpg",
    title8: "University of Tokyo",
    img9: "/CountryLogo/Japan/Waseda University.jpg",
    title9: "Stanford University",
  },
  {
    country: "China",
    flag: "/flag/China.png",
    id: 9,
    subTitle:
      "China is rapidly emerging as a leading destination for international students, offering a unique blend of ancient culture and modern innovation. With a robust education system and numerous opportunities for personal and professional growth, studying in China is an enriching experience.",
    img1: "/CountryLogo/China/Beijing Institute of Technology.jpg",

    title1: "Beijing Institute of Technology",
    img2: "/CountryLogo/China/Chinese University of Hong Kong.jpg",
    title2: "Chinese University of Hong Kong",
    img3: "/CountryLogo/China/Nanjing University.jpg",
    title3: "Nanjing University",
    img4: "/CountryLogo/China/Peking University.jpg",
    title4: "Peking University",
    img5: "/CountryLogo/China/Shandong University.jpg",
    title5: "Shandong University",
    img6: "/CountryLogo/China/Sichuan University.jpg",
    title6: "Sichuan University",
    img7: "/CountryLogo/China/Tsinghua University.jpg",
    title7: "Tsinghua University",
    img8: "/CountryLogo/China/Wuhan University.jpg",
    title8: "Wuhan University",
    img9: "/CountryLogo/China/Zhejiang University.jpg",
    title9: "Zhejiang University",
  },
  {
    country: "South Korea",
    flag: "/flag/South_Korea.png",
    id: 10,
    subTitle:
      "South Korea is home to several top-ranking universities, such as Seoul National University, KAIST, and POSTECH. These institutions offer a wide range of programs in various fields, particularly in technology, engineering, and business",
    img1: "/CountryLogo/SouthKorea/Hankuk University of Foreign Studies.jpg",
    title1: "Hankuk University of Foreign Studies",
    img2: "/CountryLogo/SouthKorea/Inha University.jpg",
    title2: "Inha University",
    img3: "/CountryLogo/SouthKorea/Korea Advanced Institute of Science and Technology.jpg",
    title3: "Korea Advanced Institute of Science and Technology",
    img4: "/CountryLogo/SouthKorea/Korea University.jpg",
    title4: "Korea University",
    img5: "/CountryLogo/SouthKorea/Kyung Hee University.jpg",
    title5: "Kyung Hee University",
    img6: "/CountryLogo/SouthKorea/Seoul National University.jpg",
    title6: "Seoul National University",
    img7: "/CountryLogo/SouthKorea/Sogang University.jpg",
    title7: "Sogang University",
    img8: "/CountryLogo/SouthKorea/Sungkyunkwan University.jpg",
    title8: "Sungkyunkwan University",
    img9: "/CountryLogo/SouthKorea/Yonsei University.jpg",
    title9: "Yonsei University.jpg",
  },
];

export const blogs = [
  {
    id: 1,
    imgSrc: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    LgImg: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Emotional Intelligence in Education: Building Resilient Learners",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Emotional intelligence (EI) is becoming a crucial element in education, helping students manage their emotions and interact with others effectively. This blog explores how incorporating EI into the curriculum can foster resilience and emotional maturity among students, preparing them for both academic and personal challenges.",
  },
  {
    id: 2,
    imgSrc: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    LgImg: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Teaching with Empathy: A Key to Emotional Intelligence",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Empathy is a cornerstone of emotional intelligence, and teachers who use empathetic approaches can create a more supportive learning environment. This article discusses strategies for incorporating empathy into teaching methods to enhance student engagement and emotional development.",
  },
  {
    id: 3,
    imgSrc: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    LgImg: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Developing Emotional Intelligence in Early Childhood Education",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Emotional intelligence is especially important in early childhood education, where children are beginning to develop social and emotional skills. This blog explores techniques for educators to nurture emotional intelligence in young learners, laying the foundation for their future interpersonal success.",
  },
  {
    id: 4,
    imgSrc: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    LgImg: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Classroom Strategies for Enhancing Emotional Intelligence",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "In this blog post, we explore practical classroom strategies that educators can implement to improve students' emotional intelligence. These techniques can help students better manage stress, communicate more effectively, and develop stronger social relationships.",
  },
  {
    id: 5,
    imgSrc: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    LgImg: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "The Role of Emotional Intelligence in Leadership within Schools",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Strong leadership is critical in educational settings, and emotional intelligence plays a vital role in how school leaders inspire and guide their teams. This blog discusses how emotionally intelligent leadership can foster a positive school culture and improve overall student outcomes.",
  },
  {
    id: 6,
    imgSrc: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    LgImg: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Emotional Intelligence: A Pathway to Inclusive Education",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Inclusion in education requires sensitivity to the emotional needs of diverse student populations. This blog post highlights how emotional intelligence can help teachers and administrators create a more inclusive and supportive learning environment for all students, regardless of their background.",
  },
  {
    id: 7,
    imgSrc: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    LgImg: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Boosting Student Well-being Through Emotional Intelligence",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Student well-being is closely tied to emotional intelligence. This article explores how schools can prioritize student mental health by promoting emotional intelligence skills such as self-awareness, empathy, and emotional regulation, ultimately leading to a healthier school environment.",
  },
  {
    id: 8,
    imgSrc: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    LgImg: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "The Impact of Emotional Intelligence on Academic Achievement",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Research has shown that emotional intelligence significantly affects academic performance. This blog delves into the connection between emotional skills and academic success, offering insights into how students can achieve better results by enhancing their emotional intelligence.",
  },
  {
    id: 9,
    imgSrc: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    LgImg: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Integrating Emotional Intelligence into School Curricula",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "How can schools effectively integrate emotional intelligence into their curricula? This blog discusses the importance of teaching emotional skills alongside academic subjects, offering practical steps for educators to incorporate emotional intelligence education into everyday lessons.",
  },
  {
    id: 10,
    imgSrc: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    LgImg: "https://i.ibb.co/0ZWkn9Z/image-12-1-66d6d885e3d32.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Building Strong Relationships in Education through EI",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Strong relationships between students, teachers, and peers are essential for effective learning. Emotional intelligence can help build these relationships by fostering communication, collaboration, and conflict resolution. This blog explores the role of EI in developing meaningful educational relationships.",
  },
  {
    id: 11,
    imgSrc: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    LgImg: "https://i.ibb.co/WpsNC35/image-12-2-66d6d8ce4500f.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Using Emotional Intelligence to Combat Bullying in Schools",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "Bullying remains a critical issue in schools, but emotional intelligence can be an effective tool for both prevention and intervention. This article examines how teaching emotional intelligence skills, such as empathy and self-regulation, can help reduce bullying incidents and create a safer school environment.",
  },
  {
    id: 12,
    imgSrc: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    LgImg: "https://i.ibb.co/kKyXvGh/image-12-66d6cc37db603.webp",
    icon: "https://i.ibb.co/C848FJ8/vector-4-66d6cda73ab92.webp",
    date: "July 24, 2024",
    title: "Fostering Emotional Intelligence in the Digital Age",
    subtitle: "Back Theme",
    extendedSubtitle: "25 Comments",
    description:
      "With the increasing presence of technology in education, it's important to consider how emotional intelligence can be fostered in the digital age. This blog explores ways to teach emotional intelligence in online classrooms and through digital tools, ensuring students continue to develop emotional skills in a tech-focused world.",
  },
];
